### ISSUE TITLE
demo在linux下运行正常，但是在mac下一直报错

### ISSUE THREAD

**Issue by Jevade** [GoAdminGroup/go-admin#13]
```
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

panic: interface conversion: interface {} is int64, not *interface {}

goroutine 1 [running]:
github.com/chenhg5/go-admin/modules/db/converter.SetResultValue(0xc0001b51e0, 0xc000164c7c, 0x4, 0x47e24c0, 0xc000172e20, 0x0, 0x0)
	/Users/liu/gofile/src/github.com/chenhg5/go-admin/modules/db/converter/sql.go:213 +0x22eb
github.com/chenhg5/go-admin/modules/db/performer.Query(0xc0003c80c0, 0x4936789, 0x39, 0xc0003f2ee0, 0x1, 0x1, 0x203000, 0x203000, 0xc0003fe600, 0xc0001b52e0)
	/Users/liu/gofile/src/github.com/chenhg5/go-admin/modules/db/performer/performer.go:56 +0x384
github.com/chenhg5/go-admin/modules/db/mysql.(*Mysql).Query(0x56e4680, 0x4936789, 0x39, 0xc0003f2ee0, 0x1, 0x1, 0x4890960, 0xa, 0xc0001b5380, 0x80)
	/Users/liu/gofile/src/github.com/chenhg5/go-admin/modules/db/mysql/mysql.go:112 +0x9c
github.com/chenhg5/go-admin/modules/db.Query(0x4936789, 0x39, 0xc0003f2ee0, 0x1, 0x1, 0x1, 0x0, 0x4894020, 0xc000196310)
	/Users/liu/gofile/src/github.com/chenhg5/go-admin/modules/db/connection.go:38 +0x150
github.com/chenhg5/go-admin/plugins/admin/models.GetRolesTable(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/liu/gofile/src/github.com/chenhg5/go-admin/plugins/admin/models/generators.go:376 +0xbb
github.com/chenhg5/go-admin/plugins/admin/models.InitTableList()
	/Users/liu/gofile/src/github.com/chenhg5/go-admin/plugins/admin/models/table.go:22 +0x112
github.com/chenhg5/go-admin/plugins/admin.(*Admin).InitPlugin(0xc0003ca140)
	/Users/liu/gofile/src/github.com/chenhg5/go-admin/plugins/admin/admin.go:39 +0x4c5
github.com/chenhg5/go-admin/engine.(*Engine).AddPlugins(0xc0001b5ea8, 0xc0001b5e88, 0x2, 0x2, 0x491a58f)
	/Users/liu/gofile/src/github.com/chenhg5/go-admin/engine/engine.go:43 +0x65
main.main()
	/Users/liu/gofile/src/github.com/chenhg5/go-admin/demo/main.go:48 +0x237
exit status 2
```

**Comment by chenhg5** [comment]
@Jevade 可以给我看下mac下的数据库结构吗

**Comment by Jevade** [comment]
https://www.dropbox.com/s/lw3xjx26sfetynj/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202018-12-06%2014.59.25.png?dl=0
https://www.dropbox.com/s/lw3xjx26sfetynj/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202018-12-06%2014.59.25.png?dl=0
这是数据的结构。还有我发现我在linux成功运行了demo但是，登录完成之后，跳转到首页不成功，还是会跳到登录页面。
稍后上传日志。

cg33 <notifications@github.com> 于2018年12月6日周四 上午10:40写道：

**Comment by zhanghoufu** [comment]
你这个是因为设置的DOMAIN的问题,因为cookie的原因导致登录又返回登录界面

**Comment by chenhg5** [comment]
问题太久，先关闭。
