### ISSUE TITLE
[Question]go-admin官方例子中把部分代码移到另一个包需要如何操作？

### ISSUE THREAD

**Issue by lujscn** [GoAdminGroup/go-admin#167]
### 问题描述 
以下示例运行正常
https://github.com/GoAdminGroup/go-admin/blob/master/examples/gin/main.go
用go run main.go运行后按下Ctrl+C，显示如下：

```
2020/02/13 01:24:54 closing database connection
```
当我把一部分代码移动到另一个包的时候，运行也正常，但按下Ctrl+C，却显示如下：
```
2020/02/13 01:31:10 closing database connection
panic: service not found

goroutine 1 [running]:
github.com/GoAdminGroup/go-admin/modules/service.List.Get(...)
        C:/Users/luyut/go/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.0/modules/service/service.go:43
github.com/GoAdminGroup/go-admin/engine.(*Engine).MysqlConnection(...)
        C:/Users/luyut/go/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.0/engine/engine.go:161
main.main()
        D:/Colin/Projects/ginAdm/main.go:29 +0x33a
exit status 2
```
## main.go
```
package main

import (
	_ "ginAdm/goadm"
	"github.com/GoAdminGroup/go-admin/engine"
	"github.com/gin-gonic/gin"
	"io/ioutil"
	"log"
	"os"
	"os/signal"
)

func main() {
	r := gin.Default()

	gin.SetMode(gin.ReleaseMode)
	gin.DefaultWriter = ioutil.Discard

	eng := engine.Default()

	go func() {
		_ = r.Run(":9033")
	}()

	quit := make(chan os.Signal)
	signal.Notify(quit, os.Interrupt)
	<-quit
	log.Print("closing database connection")
	eng.MysqlConnection().Close()
}
```
## ginadm包
```
package goadm

import (
	_ "github.com/GoAdminGroup/go-admin/adapter/gin"
	_ "github.com/GoAdminGroup/go-admin/modules/db/drivers/mysql"

	"github.com/GoAdminGroup/go-admin/engine"
	"github.com/GoAdminGroup/go-admin/examples/datamodel"
	"github.com/GoAdminGroup/go-admin/modules/config"
	"github.com/GoAdminGroup/go-admin/modules/language"
	"github.com/GoAdminGroup/go-admin/plugins/admin"
	"github.com/GoAdminGroup/go-admin/plugins/example"
	"github.com/GoAdminGroup/go-admin/template"
	"github.com/GoAdminGroup/go-admin/template/chartjs"
	"github.com/GoAdminGroup/go-admin/template/types"
	"github.com/GoAdminGroup/themes/adminlte"
	"github.com/gin-gonic/gin"
)

func init()  {
	r := gin.Default()

	eng := engine.Default()

	cfg := config.Config{
		Databases: config.DatabaseList{
			"default": {
				Host:       "127.0.0.1",
				Port:       "3306",
				User:       "root",
				Pwd:        "root",
				Name:       "godmin",
				MaxIdleCon: 50,
				MaxOpenCon: 150,
				Driver:     config.DriverMysql,
			},
		},
		UrlPrefix: "admin",
		Store: config.Store{
			Path:   "./uploads",
			Prefix: "uploads",
		},
		Language:    language.CN,
		IndexUrl:    "/",
		Debug:       true,
		ColorScheme: adminlte.ColorschemeSkinBlack,
	}

	adminPlugin := admin.NewAdmin(datamodel.Generators).AddDisplayFilterXssJsFilter()

	template.AddComp(chartjs.NewChart())

	examplePlugin := example.NewExample()

	if err := eng.AddConfig(cfg).
		AddPlugins(adminPlugin, examplePlugin).
		Use(r); err != nil {
		panic(err)
	}

	r.Static("/uploads", "./uploads")

}
```

**Comment by chenhg5** [comment]
此问题跟框架无关，属于基础代码运行问题，时间较久先关闭，如还有问题可以再次新开一个issue。
