### ISSUE TITLE
[Question] panic: gin adapter SetApp: wrong parameter

### ISSUE THREAD

**Issue by weidongbcn** [GoAdminGroup/go-admin#302]
### bug 描述 [详细地描述 bug，让大家都能理解]

```
2020-08-05T19:32:11.009+0200	INFO	logger/logger.go:257	=====> 初始化数据库连接
2020-08-05T19:32:11.011+0200	INFO	logger/logger.go:257	=====> 初始化配置
2020-08-05T19:32:11.018+0200	INFO	logger/logger.go:257	=====> 初始化错误代码
2020-08-05T19:32:11.018+0200	INFO	logger/logger.go:257	=====> 初始化导航栏按钮
2020-08-05T19:32:11.018+0200	INFO	logger/logger.go:257	=====> 初始化插件
panic: gin adapter SetApp: wrong parameter

goroutine 1 [running]:
main.startServer()
	C:/Users/weido/go/src/testService/test_admin/main.go:38 +0x6d2
main.main()
	C:/Users/weido/go/src/testService/test_admin/main.go:22 +0x27

Process finished with exit code 2
```

![image](https://user-images.githubusercontent.com/23153588/89445141-0ab34680-d753-11ea-8ad9-26c64ac85306.png)

**Comment by chenhg5** [comment]
@weidongbcn 看着像依赖问题，检查一下你的依赖。最好统一为使用go mod运行。

**Comment by weidongbcn** [comment]
![Snipaste_2020-08-06_05-44-43](https://user-images.githubusercontent.com/23153588/89504849-fad64980-d7c8-11ea-80d7-ae45c9ac5bc2.png)

这里需要修正

**Comment by weidongbcn** [comment]
修正好了这个问题可以关闭了。
