### ISSUE TITLE
Error Display table "runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by zhjianxia** [GoAdminGroup/go-admin#312]
For mysql table with "datetime" column: 

```
+-----------------+-------------+------+-----+---------+----------------+
| Field           | Type        | Null | Key | Default | Extra          |
+-----------------+-------------+------+-----+---------+----------------+
| ID              | int         | NO   | PRI | NULL    | auto_increment |
| MQTTRESOURCE_ID | varchar(50) | YES  |     | NULL    |                |
| REGION_ID       | varchar(20) | YES  |     | NULL    |                |
| CUSTOMER_ID     | varchar(50) | YES  |     | NULL    |                |
| USER_ID         | varchar(50) | YES  |     | NULL    |                |
| IS_DELETE       | tinyint(1)  | YES  |     | NULL    |                |
| CREATE_TIME     | datetime    | YES  |     | NULL    |                |
| MODIFY_TIME     | datetime    | YES  |     | NULL    |                |
+-----------------+-------------+------+-----+---------+----------------+
```

Failed to display table content: 

![image](https://user-images.githubusercontent.com/35085514/90388632-b006dc80-e0ba-11ea-9014-642720beafbf.png)

Stack error:

```
 2020-08-17T18:52:43.960+0800	logger/logger.go:322	[GoAdmin]  200   GET    /admin/info/mqtt_resource
2020-08-17T18:52:43.962+0800	ERROR	logger/logger.go:285	runtime error: invalid memory address or nil pointer dereference
2020-08-17T18:52:43.963+0800	ERROR	logger/logger.go:285	goroutine 290 [running]:
runtime/debug.Stack(0xc000116430, 0x112fe02, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/GoAdminGroup/go-admin/plugins/admin/controller.(*Handler).GlobalDeferHandler(0xc0000d61e0, 0xc000612180)
	/usr/local/go/work/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.15/plugins/admin/controller/handler.go:32 +0xc6
panic(0x112fe60, 0x1f5be50)
	/usr/local/go/src/runtime/panic.go:967 +0x166
github.com/GoAdminGroup/go-admin/template/types.FieldDisplay.ToDisplay(0x0, 0x0, 0x0, 0x0, 0xc000511250, 0x3, 0xc000511250, 0x3, 0xc000459230, 0x0, ...)
	/usr/local/go/work/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.15/template/types/display.go:39 +0x5d
github.com/GoAdminGroup/go-admin/plugins/admin/modules/table.(*DefaultTable).getTempModelData(0xc0006123c0, 0xc000459230, 0x12310d8, 0x1, 0x1, 0x126f29e, 0x2, 0xa, 0x1231373, 0x2, ...)
	/usr/local/go/work/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.15/plugins/admin/modules/table/default.go:304 +0x35d
github.com/GoAdminGroup/go-admin/plugins/admin/modules/table.(*DefaultTable).getDataFromDatabase(0xc0006123c0, 0x12310d8, 0x1, 0x1, 0x126f29e, 0x2, 0xa, 0x1231373, 0x2, 0x21ae348, ...)
	/usr/local/go/work/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.15/plugins/admin/modules/table/default.go:521 +0xd8f
github.com/GoAdminGroup/go-admin/plugins/admin/modules/table.(*DefaultTable).GetData(0xc0006123c0, 0x12310d8, 0x1, 0x1, 0x126f29e, 0x2, 0xa, 0x1231373, 0x2, 0x21ae348, ...)
	/usr/local/go/work/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.15/plugins/admin/modules/table/default.go:126 +0xb16
github.com/GoAdminGroup/go-admin/plugins/admin/controller.(*Handler).showTableData(0xc0000d61e0, 0xc000612180, 0xc0002fc109, 0xd, 0x12310d8, 0x1, 0x1, 0x126f29e, 0x2, 0xa, ...)
	/usr/local/go/work/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.15/plugins/admin/controller/show.go:71 +0x208
github.com/GoAdminGroup/go-admin/plugins/admin/controller.(*Handler).showTable(0xc0000d61e0, 0xc000612180, 0xc0002fc109, 0xd, 0x12310d8, 0x1, 0x1, 0x126f29e, 0x2, 0xa, ...)
	/usr/local/go/work/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.15/plugins/admin/controller/show.go:101 +0xd8
github.com/GoAdminGroup/go-admin/plugins/admin/controller.(*Handler).ShowInfo(0xc0000d61e0, 0xc000612180)
	/usr/local/go/work/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.15/plugins/admin/controller/show.go:61 +0x2e8
github.com/GoAdminGroup/go-admin/context.(*Context).Next(0xc000612180)
	/usr/local/go/work/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.15/context/context.go:101 +0x44
github.com/GoAdminGroup/go-admin/plugins/admin/modules/guard.(*Guard).CheckPrefix(0xc0004922d0, 0xc000612180)
	/usr/local/go/work/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.15/plugins/admin/modules/guard/guard.go:51 +0x1d4
github.com/GoAdminGroup/go-admin/context.(*Context).Next(0xc000612180)
	/usr/local/go/work/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.15/context/context.go:101 +0x44
github.com/GoAdminGroup/go-admin/modules/auth.(*Invoker).Middleware.func1(0xc000612180)
	/usr/local/go/work/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.15/modules/auth/middleware.go:132 +0x301
github.com/GoAdminGroup/go-admin/context.(*Context).Next(0xc000612180)
	/usr/local/go/work/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.15/context/context.go:101 +0x44
github.com/GoAdminGroup/go-admin/plugins/admin.(*Admin).globalErrorHandler(0xc000112040, 0xc000612180)
	/usr/local/go/work/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.15/plugins/admin/router.go:104 +0x7a
github.com/GoAdminGroup/go-admin/context.(*Context).Next(0xc000612180)
	/usr/local/go/work/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.15/context/context.go:101 +0x44
github.com/GoAdminGroup/go-admin/adapter/gin.(*Gin).AddHandler.func1(0xc000012000)
	/usr/local/go/work/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.15/adapter/gin/gin.go:91 +0x2a3
github.com/gin-gonic/gin.(*Context).Next(0xc000012000)
	/usr/local/go/work/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/gin-gonic/gin.RecoveryWithWriter.func1(0xc000012000)
	/usr/local/go/work/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 +0x60
github.com/gin-gonic/gin.(*Context).Next(0xc000012000)
	/usr/local/go/work/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc000012000)
	/usr/local/go/work/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 +0xe1
github.com/gin-gonic/gin.(*Context).Next(0xc000012000)
	/usr/local/go/work/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000040140, 0xc000012000)
	/usr/local/go/work/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 +0x666
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000040140, 0x177a000, 0xc00016a1c0, 0xc000168100)
	/usr/local/go/work/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x14d
net/http.serverHandler.ServeHTTP(0xc0002d2000, 0x177a000, 0xc00016a1c0, 0xc000168100)
	/usr/local/go/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc00025a1e0, 0x177c840, 0xc000612000)
	/usr/local/go/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2933 +0x35c
```

**Comment by chenhg5** [comment]
@zhjianxia Change primary key field named ID to id, or you can specify the primary key name like this:

```
table.NewDefaultTable(table.Config{
		...
		PrimaryKey: table.PrimaryKey{
			Type: db.Int,
			Name: "ID",
		},
		...
	})
```
