### ISSUE TITLE
[BUG]最新版本 panic: service not found

### ISSUE THREAD

**Issue by Juntaran** [GoAdminGroup/go-admin#314]
### bug 描述 

按照官方样例  adm init web 之后，生成 sql 写入 db
make serve 时直接 panic

```
go run .
GoAdmin is now running.
Running in "debug" mode. Switch to "release" mode in production.

2020-08-19T17:21:41.861+0800    INFO    engine/engine.go:379    =====> 初始化数据库连接
panic: service not found

goroutine 1 [running]:
github.com/GoAdminGroup/go-admin/modules/service.List.Get(...)
        /goWorkspace/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.16/modules/service/service.go:43
github.com/GoAdminGroup/go-admin/modules/db.GetConnection(0xc0004c9290, 0xc0004c9bf0, 0xc00031f778)
        /goWorkspace/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.16/modules/db/connection.go:99 +0x1a9
github.com/GoAdminGroup/go-admin/engine.(*Engine).initDatabase(0xc00050c700, 0xc0004e6700)
        /goWorkspace/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.16/engine/engine.go:173 +0x414
github.com/GoAdminGroup/go-admin/engine.(*Engine).AddConfigFromJSON(0xc00050c700, 0x4bbcebc, 0xd, 0x7)
        /goWorkspace/pkg/mod/github.com/!go!admin!group/go-admin@v1.2.16/engine/engine.go:149 +0xc6
main.startServer()
        /goWorkspace/src/dashboard/main.go:35 +0x233
main.main()
        /goWorkspace/src/dashboard/main.go:23 +0x20
exit status 2
make: *** [serve] Error 1
```

### 复现步骤

最新版本 1.2.16 按照官网样例走
> make init module=dashboard
> GORPOXY=https://goproxy.io make install
> make serve

### 期望结果

demo 启动成功

### 版本信息:

- GoAdmin 版本：1.2.16
- golang 版本：1.14.3
- 浏览器环境：chrome
- 开发环境：mac

**Comment by yangguangwuwu** [comment]
不是 bug， 是没连接上数据库

**Comment by chenhg5** [comment]
@Juntaran 重新下载adm，此前有修复了一下：http://doc.go-admin.cn/zh/install
